version: "3"
services:
  python:
    container_name: python
    build:
      context: .
      dockerfile: dockerfile
    ports:
      - "5000:5000"
    networks:
      - python
    environment:
      FLASK_APP: src.infrastructure.api.app
networks:
  python:
    name: python
